theme: jekyll-theme-hacker
title: Les ressources de Jingl3s
description: Du contenu en tout genre avec l'information ou non sans se prendre la tete
# remote_theme: "mmistakes/minimal-mistakes@4.20.2"
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Los_Angeles # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# include:
#   - _pages
#   - bricolage

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
# defaults:
#   # _posts
#   - scope:
#       path: ""
#       type: posts
#     values:
#       layout: single
#       author_profile: true
#       read_time: true
#       comments: true
#       related: true

menu:
  main:
  - identifier: homee
    name: Home
    title: Home
    url: /
    weight: 1
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 0
  - identifier: tags
    name: Tags
    title: Tags
    url: /tags/
    weight: 0